name: Workflow

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Log environment variables
        run: echo $GITHUB_WORKFLOW $GITHUB_REF $GITHUB_REPOSITORY $GITHUB_RUN_ID
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
        env:
          CI: true
      - name: Deploy to GitHub pages
        run: |
          git config user.email "oliver.viljamaa@gmail.com"
          git config user.name "Oliver Viljamaa"
          yarn deploy -t ${{ secrets.GITHUB_TOKEN }}
